interface RandomNamesItems {
    key: number;
    value: string;
}

const RandomNames: RandomNamesItems[] =[
    { key: 1, value: "Thalwyn the Brave" },
    { key: 2, value: "Eldarion Stormblade" },
    { key: 3, value: "Lorelei Silverleaf" },
    { key: 4, value: "Gareth Ironheart" },
    { key: 5, value: "Isolde Shadowhunter" },
    { key: 6, value: "Branwen Frostbane" },
    { key: 7, value: "Draven Blackthorn" },
    { key: 8, value: "Rowan Lightbringer" },
    { key: 9, value: "Elara Moonshadow" },
    { key: 10, value: "Soren Firewalker" },
    { key: 11, value: "Faelan Brightblade" },
    { key: 12, value: "Lyanna Starfall" },
    { key: 13, value: "Caelum Skywatcher" },
    { key: 14, value: "Aurelia Dawnseeker" },
    { key: 15, value: "Rhydian Wolfsbane" },
    { key: 16, value: "Elysia Windrider" },
    { key: 17, value: "Thorn Ironfist" },
    { key: 18, value: "Morwen Shadowcaster" },
    { key: 19, value: "Brynmor Stormborn" },
    { key: 20, value: "Seraphina Swiftblade" },
    { key: 21, value: "Thalwyn the Brave" },
    { key: 22, value: "Eldarion Stormblade" },
    { key: 23, value: "Lorelei Silverleaf" },
    { key: 24, value: "Gareth Ironheart" },
    { key: 25, value: "Isolde Shadowhunter" },
    { key: 26, value: "Branwen Frostbane" },
    { key: 27, value: "Draven Blackthorn" },
    { key: 28, value: "Rowan Lightbringer" },
    { key: 29, value: "Elara Moonshadow" },
    { key: 30, value: "Soren Firewalker" },
    { key: 31, value: "Alistair Darkblade" },
    { key: 32, value: "Lysandra Nightshade" },
    { key: 33, value: "Cassius Ironwood" },
    { key: 34, value: "Aurelius Shadowflame" },
    { key: 35, value: "Sylvana Stormwatcher" },
    { key: 36, value: "Valerian Frostwind" },
    { key: 37, value: "Miranda Moonlight" },
    { key: 38, value: "Ragnar Thunderheart" },
    { key: 39, value: "Ariana Sunfire" },
    { key: 40, value: "Darius Nightblade" },
    { key: 41, value: "Thorin Stonehammer" },
    { key: 42, value: "Aurora Dawnstar" },
    { key: 43, value: "Kaelen Shadowthorn" },
    { key: 44, value: "Eowyn Silverwind" },
    { key: 45, value: "Cedric Stormborn" },
    { key: 46, value: "Arianna Sunbeam" },
    { key: 47, value: "Luther Ironsides" },
    { key: 48, value: "Serafina Moonbeam" },
    { key: 49, value: "Eldric Shadowcaster" },
    { key: 50, value: "Galadriel Fireheart" },
    { key: 51, value: "Alistair Darkblade" },
    { key: 52, value: "Isabella Frostbane" },
    { key: 53, value: "Gideon Nightshade" },
    { key: 54, value: "Ariadne Stormcaller" },
    { key: 55, value: "Lucian Silverblade" },
    { key: 56, value: "Elara Swiftfoot" },
    { key: 57, value: "Gavin Frostfire" },
    { key: 58, value: "Freya Moonshadow" },
    { key: 59, value: "Thorin Stormrider" },
    { key: 60, value: "Leandra Darkmoon" },
    { key: 61, value: "Rohan Shadowcaster" },
    { key: 62, value: "Elena Frostheart" },
    { key: 63, value: "Raiden Sunstrike" },
    { key: 64, value: "Arabella Windrunner" },
    { key: 65, value: "Valeria Ironsoul" },
    { key: 66, value: "Erik Shadowblade" },
    { key: 67, value: "Anastasia Stormborn" },
    { key: 68, value: "Luther Sunhammer" },
    { key: 69, value: "Cassandra Darkwater" },
    { key: 70, value: "Aldric Shadowflame" },
    { key: 71, value: "Elowen Stormwatcher" },
    { key: 72, value: "Thorne Nightstalker" },
    { key: 73, value: "Elena Frostbloom" },
    { key: 74, value: "Aurora Dawnwhisper" },
    { key: 75, value: "Lucian Stormblade" },
    { key: 76, value: "Rowan Shadowdancer" },
    { key: 77, value: "Isolde Frostwind" },
    { key: 78, value: "Alistair Stormbringer" },
    { key: 79, value: "Freya Darkmoon" },
    { key: 80, value: "Erik Ironheart" },
    { key: 81, value: "Cassandra Shadowbloom" },
    { key: 82, value: "Rohan Frostfire" },
    { key: 83, value: "Anastasia Stormcaller" },
    { key: 84, value: "Luther Shadowflame" },
    { key: 85, value: "Elowen Moonwhisper" },
    { key: 86, value: "Thorne Nightwind" },
    { key: 87, value: "Elena Stormbloom" },
    { key: 88, value: "Aurora Shadowwhisper" },
    { key: 89, value: "Lucian Dawnblade" },
    { key: 90, value: "Rowan Frostdancer" },
    { key: 91, value: "Isolde Stormwind" },
    { key: 92, value: "Alistair Darkthorn" },
    { key: 93, value: "Freya Moonlight" },
    { key: 94, value: "Erik Shadowflame" },
    { key: 95, value: "Cassandra Nightbloom" },
    { key: 96, value: "Rohan Frostshadow" },
    { key: 97, value: "Anastasia Stormblade" },
    { key: 98, value: "Luther Nightflame" },
    { key: 99, value: "Elowen Shadowwhisper" },
    { key: 100, value: "Thorne Moonwind" },
    { key: 101, value: "Aurelia" },
    { key: 102, value: "Ignatius" },
    { key: 103, value: "Draco" },
    { key: 104, value: "Vermithrax" },
    { key: 105, value: "Saphira" },
    { key: 106, value: "Falkor" },
    { key: 107, value: "Viserion" },
    { key: 108, value: "Drogon" },
    { key: 109, value: "Rhaegal" },
    { key: 110, value: "Meraxes" },
];

export default RandomNames;