interface RingsItem {
    key: number;
    value: string;
}

const Rings: RingsItem[] = [
    { key: 1, value: 'Widow’s band\n------------\nMG: 1\nSA: Heal' },
    { key: 2, value: 'Missing link\n------------\nBR: 1\nMG: 1' },
    { key: 3, value: 'Traveller’s band\n------------\nBR: 1\nMG: 1\nSA: Charm' },
    { key: 4, value: 'Lightning ring\n------------\nSA: Lightning' },
    { key: 5, value: 'Grave dust ring\n------------\nBR: 1' },
    { key: 6, value: 'Scholar’s circle\n------------\nSA: Eureka!' },
    { key: 7, value: 'Blackfire ring\n------------\nSA: Sear' },
    { key: 8, value: 'Circle of thorns\n------------\nSA: Thorns' },
    { key: 9, value: 'Splintered band (W)\n------------\nBR: 2\nSA: Retaliation' },
    { key: 10, value: 'My precious\n------------\nAR: 1\nSA: Vanish' },
    { key: 11, value: 'Wayfarer’s ring\n------------\nBR: 1\nMG: 1\nSA: Charm' },
    { key: 12, value: 'Vermillion rage\n------------\nMG: 1\nSA: Bleed' },
    { key: 13, value: 'Clymonistra’s folly\n------------\nMG: 1\nAR: 1\nSA: Cly’s adornments' },
    { key: 14, value: 'Finger of fire\n------------\nBR: 1\nSA: Sear' },
    { key: 15, value: 'Ring of the marshes\n------------\nBR: 1\nMG: 1\nSA: Swamp legs' },
    { key: 16, value: 'Steadfast ring (M)\n------------\nAR: 1\nSA: Steadfast' },
    { key: 17, value: 'Serpent’s coil (R + W)\n------------\nBR: 1\nSA: Immobilise' },
    { key: 18, value: 'Band of conquest (R + W)\n------------\nAR: 1\nSA: Fortitude' },
    { key: 19, value: 'Abyssal brimstone\n------------\nMG: 1\nSA: Cauterise' },
    { key: 20, value: 'Avatar’s circle (M)\n------------\nMG: 1\nSA: Overload' },
    { key: 21, value: 'Lupine lapis\n------------\nBR: 1\nSA: Bleed' },
    { key: 22, value: 'Mender’s marcasite\n------------\nMG: 1\nSA: Regrowth' },
    { key: 23, value: 'Cutter’s cornelian\n------------\nAR: 1\nSA: Piercing' },
    { key: 24, value: 'Magpie’s mischief\n------------\nAR: 1\nSA: Steal' },
    { key: 25, value: 'Dryad’s band\n------------\nBR: 1\nSA: Thorn armour' },
    { key: 26, value: 'Khana’s revenge (W)\n------------\nBR: 2\nSA: Bleed' },
    { key: 27, value: 'Wrath of ages (M)\n------------\nMG: 2\nSA: Rust' },
    { key: 28, value: 'Leader of the pack\n------------\nBR: 1\nSA: Dominate' },
    { key: 29, value: 'Sinister shadows\n------------\nBR: 1\nMG: 1\nSA: Vanish' },
    { key: 30, value: 'Blood winter\n------------\nBR: 1\nSA: Leech' },
    { key: 31, value: 'Hunger\n------------\nBR: 2\nSA: Leech' },
    { key: 32, value: 'Tooth ‘n claw (W)\n------------\nSP: 1\nBR: 1\nSA: Sideswipe' },
    { key: 33, value: 'Martyr’s blood\n------------\nMG: 1\nAR: 1\nSA: Martyr' },
    { key: 34, value: 'Seven stars (R + W)\n------------\nBR: 2\nSA: Heal' },
    { key: 35, value: 'Wytchwood thorn (R + W)\n------------\nBR: 1\nSA: Thorns' },
    { key: 36, value: 'Zul’s zapper\n------------\nBR: 1\nMG: 1\nSA: Zapped!' },
    { key: 37, value: 'Band of elements (W + M)\n------------\nMG: 2\nSA: Lightning' },
    { key: 38, value: 'Budak’s signet (W + M)\n------------\nBR: 1\nMG: 1\nSA: Steal' },
    { key: 39, value: 'Spider sapphire (R + M)\n------------\nMG: 1\nAR: 1\nSA: Webbed' },
    { key: 40, value: 'Serpentine spiral (R + M)\n------------\nBR: 1\nAR: 1\nSA: Immobilise' },
    { key: 41, value: 'Conduit of shadow (M)\n------------\nMG: 3\nSA: Overload' },
    { key: 42, value: 'Stria of Genna (M)\n------------\nMG: 1\nAR: 2\nSA: Shock!' },
];

export default Rings;
